### ISSUE TITLE
Vielen Dank und Nebensächliches

### ISSUE THREAD

**Issue by Nihlo** [heroesiiifan/HoMM3-German#2]
Hey, vielen Dank für die ganze Arbeit. Ich teste gerade ausführlich und bin begeistert. Ich habe ein paar Mini Fehler gefunden, nur falls es überhaupt noch interessiert: 

1.: https://ibb.co/qrKfgrF
Man sieht, die Team Bezeichnungen sind sehr inkonsistent. Es gibt "Team" (original afair) aber auch "Verbündete" und "Allierte". Team auch als "Mapname/Team" und wie ursprünglich: "Mapname (Team)". Außerdem Fälle bei denen Team angegeben ist, aber es eben die Single-Variante ist, wie hier rot markiert. Außerdem hat man noch eine amerikanische Datumsanzeige, also Monat/Tag/Jahr statt Tag/Monat/Jahr. 

2.: https://ibb.co/jk0jhSw
Ein Tooltip wurde nicht übersetzt, kommt von der übersetzten Funktion "Krieg der Magier" oben links in den Szenarios. Kommt ja mit H3 HD+ afaik.

3.: https://ibb.co/P1DFpxb
"Random", "Autosave" und "Battle" sind offensichtlich englische Begriffe. Bilde mir zumindest ein die "Random" Karten hatten mal eine deutsche Bezeichnung in SoD. Das Autosave hat auch seltsame zusätzliche Leerzeichen. 

4.: https://ibb.co/0B97HGj
Was ich auch nicht verstehe, warum sind 2 der Chronicles doppelt ? Sind auch leicht unterschiedliche Beschreibungen. Manche Namen sind auch offensichtlich noch englisch. 

5.: https://ibb.co/D890rYn
Was mir im Town-Screen auffiel, zum einen sind die +X Wachstumsraten der Kreaturen verschwunden, liegt aber glaub ich an HD+ mit dem ausführlicheren Tooltip ? Außerdem sind die Tooltips der Ressourcen in der unteren Leiste nach rechts verschoben, Gold kommt zB bereits wieder wenn man mit der Mouse über dem Holz ist, Holz zwischen Holz und Quecksilber etc. Scheint auch nicht an der höhere  Auflösung zu liegen. Ist der einzige verschobene Tooltip Offset der mir aufgefallen ist.

6.: https://ibb.co/z6QR6SN
Liegt vermutlich nicht an der Übersetzung, aber ist mir zumindest früher im englischen Complete+HD+ aufgefallen: die braune Leiste die scheinbar dann auftaucht wenn mehrere Fenster geöffnet sind, zB nach einem Kampf. Die neuen Kampfergebnis akzeptieren oder erneut spielen Buttons nach dem Kampf haben keine Tooltips, bilde mir ein früher stand da irgendwas auf englisch. 

Also insgesamt nichts wichtiges, fiel mir nur auf und wollte es melden wenn sich schon jemand die ganze Mühe gemacht hat.

**Comment by heroesiiifan** [comment]
> Hey, vielen Dank für die ganze Arbeit. Ich teste gerade ausführlich und bin begeistert. Ich habe ein paar Mini Fehler gefunden, nur falls es überhaupt noch interessiert:

Schön, dass es für dich von Nutzen ist und dir Freude bereitet. :)

> 1.: https://ibb.co/qrKfgrF Man sieht, die Team Bezeichnungen sind sehr inkonsistent. Es gibt "Team" (original afair) aber auch "Verbündete" und "Allierte". Team auch als "Mapname/Team" und wie ursprünglich: "Mapname (Team)". Außerdem Fälle bei denen Team angegeben ist, aber es eben die Single-Variante ist, wie hier rot markiert. Außerdem hat man noch eine amerikanische Datumsanzeige, also Monat/Tag/Jahr statt Tag/Monat/Jahr.

Ja, das sind noch so Überbleibsel von der teilautomatischen Übersetzung. Sollte aber nur AB und HotA betreffen. Die Hauptspiel und SoD-Szenarien sind Original-Übersetzungen. Wenn jemand die Szenarien-Übersetzungen perfektionieren möchte: Einfach mit den Karteneditor Titel (bzw. Ingame-Texte) anpassen und mir übermitteln. Ich pflege das dann gerne ein. :)

Habe aber mal die Titel angepasst. Jetzt steht überall "(Team)". Außer bei RoE, da steht "/Team". Die originalen Übersetzungen sind da nicht konsistent. Wollte aber nicht alles anpassen. Den einen Fall mit dem Single/Team-Fehler hab ich angepasst. Ist übrigens ein Fehler, der bei der Original-Übersetzung gemacht wurde - (gekaufte) Software ist nie perfekt. :)

Die Datumsanzeige ist nicht ganz so trivial. Da muss man einen Patch für das Hauptspiel machen. Was Reverse-Engeneering bedeutet (siehe "NoToLower"). Übrigens betrifft die nur das Hauptspiel (nicht HotA, da ist es eine "deutsche" Anzeige), warum auch immer.

> 2.: https://ibb.co/jk0jhSw Ein Tooltip wurde nicht übersetzt, kommt von der übersetzten Funktion "Krieg der Magier" oben links in den Szenarios. Kommt ja mit H3 HD+ afaik.

Das ist mir auch schon aufgefallen. Aber scheinbar ist der Text in HD+ hardgecodet. Denn selbst in dem englischen Übersetzungs-File taucht er nicht auf.

> 3.: https://ibb.co/P1DFpxb "Random", "Autosave" und "Battle" sind offensichtlich englische Begriffe. Bilde mir zumindest ein die "Random" Karten hatten mal eine deutsche Bezeichnung in SoD. Das Autosave hat auch seltsame zusätzliche Leerzeichen.

Das ist auch vermutlich hardcoded. Ich denke, dass es auch in den anderen Sprachen nicht übersetzt wird. Habe es aber nicht kontrolliert.

> 4.: https://ibb.co/0B97HGj Was ich auch nicht verstehe, warum sind 2 der Chronicles doppelt ? Sind auch leicht unterschiedliche Beschreibungen. Manche Namen sind auch offensichtlich noch englisch.

Offiziell gibt es nur diese hier offiziell in deutsch (6 Stück):
https://github.com/heroesiiifan/HoMM3-German/tree/master/additional_files/translation/campaign/chronicles

Zu diesen gibt es aber eine Fan-Übersetzung (4 Stück):
https://github.com/heroesiiifan/HoMM3-German/tree/master/additional_files/translation/campaign/extra

Insgesamt gab es 8 Chronicles. 6 wurden offiziell übersetzt. D.h. insgesamt gibt es zwei doppelt und man hat da die Auswahl zwischen Fan-Übersetzung (die mit "(de)" im Dateinamen) und offizieller Übersetzung.

> 5.: https://ibb.co/D890rYn Was mir im Town-Screen auffiel, zum einen sind die +X Wachstumsraten der Kreaturen verschwunden, liegt aber glaub ich an HD+ mit dem ausführlicheren Tooltip ? Außerdem sind die Tooltips der Ressourcen in der unteren Leiste nach rechts verschoben, Gold kommt zB bereits wieder wenn man mit der Mouse über dem Holz ist, Holz zwischen Holz und Quecksilber etc. Scheint auch nicht an der höhere Auflösung zu liegen. Ist der einzige verschobene Tooltip Offset der mir aufgefallen ist.

Habs gerade mal im Complete in Englisch probiert (kann man ja schnell umschalten). Da ist es auch der Fall. Ist wohl noch ein Bug in HD+.

> 6.: https://ibb.co/z6QR6SN Liegt vermutlich nicht an der Übersetzung, aber ist mir zumindest früher im englischen Complete+HD+ aufgefallen: die braune Leiste die scheinbar dann auftaucht wenn mehrere Fenster geöffnet sind, zB nach einem Kampf. Die neuen Kampfergebnis akzeptieren oder erneut spielen Buttons nach dem Kampf haben keine Tooltips, bilde mir ein früher stand da irgendwas auf englisch.

Ja, ich denke auch, dass das eher ein HD+-Thema ist.

> Also insgesamt nichts wichtiges, fiel mir nur auf und wollte es melden wenn sich schon jemand die ganze Mühe gemacht hat.

Alles gut. :)
Und danke für den Input. Dann ist es hier auch dokumentiert. :)

**Comment by Nihlo** [comment]
Ah danke für das Feedback. Das meiste hab ich mir schon gedacht, sind ja wirklich nur Kleinigkeiten mit denen jeder leben können sollte. 

Was mir noch aufgefallen ist, das erwähnte SP_Plugin: https://github.com/RoseKavalier/H3Plugins/releases
hat ja an sich inzwischen eine deutsche Übersetzung im Installer. Ist das deine oder sollte man dann nochmal mit Dateien aus deinem Paket überschreiben ?

Im SP-Deutsch fehlen zumindest Umlaute^^ Ist vllt nur Google-Translate vom SP-Autor:
https://ibb.co/2P7zKCw

**Comment by heroesiiifan** [comment]
Kein Problem. :)

Ja, am besten nochmal überschrieben. Wurde in SP noch nicht intigriert. Da existiert schon lange ein Issue (siehe hier: https://github.com/RoseKavalier/H3Plugins/issues/18).

**Comment by Nihlo** [comment]
Ach ist in die Source-Files, da hab ich natürlich als letztes gesucht. 

Hab die deu.json ersetzt aber die Mod/Launcher nimmt sie so nicht unregistriert scheinbar:

https://ibb.co/gjwcSLS
https://ibb.co/XZMsdhb
https://ibb.co/0ygJpg3
https://ibb.co/9wxj7wk

**Comment by heroesiiifan** [comment]
Doch, sollte er.

Da sind allerdings neue Strings dazugekommen. Das wird das Problem sein. Einfach die Änderungen übernehmen:
https://github.com/heroesiiifan/HoMM3-German/commit/c347111dc416f6b44cee87ee82266a1c45d255bb

**Comment by Nihlo** [comment]
works, many thanks

**Comment by Nihlo** [comment]
Was mir noch aufgefallen ist, vom Kampagnen Menü kommt man nicht mit einem "Zurück" Button zurück wie in den anderen Fällen, sondern mit einem "Ende" Button wie dem, mit dem man im Hauptmenü ganz aus dem Spiel kommt. Ist aber scheinbar in der englischen Version auch so:
![e7](https://user-images.githubusercontent.com/26931653/201243459-66fa0128-8b97-41bd-81ce-4f697bcc7963.jpg)

Und falls du noch mehr offiziellen Content zur Sammlung hinzufügen/übersetzen willst, ich hab noch die original Demo Map gefunden^^ Gab wohl keine deutsche Demo:
https://www.file-upload.net/download-15037719/H3demo.h3m.html
Ist eine leicht abgewandelte Version von "Dead and Buried" mit einem Zeitlimit und ein paar Demo-Text-Popups. Keine Ahnung obs noch Unterschiede auf der Karte gibt. In der Demo kommt man direkt ins Spiel, war also auch Schwierigkeitsgrad, Zufallsheld und Zufallsboni vorgegeben. Dazu manchmal nur 1 creature dwelling in der Startstadt...für Anfänger sogar recht knackig. 

Naja, denk jetzt fallen mir nicht mal mehr Kleinigkeiten ein^^

**Comment by heroesiiifan** [comment]
Hallo @Nihlo

Stimmt, gut gesehen. Das mit dem Button war ein Fehler. Wird behoben. Mach aber erstmal keinen neuen Release. Ggf. die geänderte Datei händisch in den Mod-Ordner packen. :)

Dankeschön für die Demo. Ich glaube so Wahnsinnig viel Sinn macht das nicht, die beizulegen.
De facto gibts von der Text-Seite ein Event mehr:
> Name:
> Day 1 - Welcome to the Heroes of Might and Magic III Demo
> Message:
> Welcome to the Heroes of Might and Magic III demo.		You must defeat all your enemies in four weeks.		Who do you wish to fight first... the dead or the buried?

**Comment by heroesiiifan** [comment]
Erledigt mit https://github.com/heroesiiifan/HoMM3-German/commit/486f706b06e9a3721ae5bfecbb8cfa3347be1d9e

> Naja, denk jetzt fallen mir nicht mal mehr Kleinigkeiten ein^^

Früher oder später fällt einem immer was auf. :D

**Comment by Nihlo** [comment]
Poste nur nochmal hier rein weil vermutlich nichts zu tun ist.

1. SoD_SP hatte ein kleines Update:
https://docs.google.com/document/d/1X2s6Nc1H4s_H_fGI85jYkoxmNKEFtq5NCs0Y8LaJvg0/edit
schaut so aus als wäre nichts neues zum übersetzen dabei. Logischerweise kommt beim updaten dann wieder die fehlerhafte deutsche Datei rein. Vllt kannst du deine deutsche Datei etwas prominenter in der zip positionieren, ich such mir da jedes mal nen Wolf^^ 

2. Im Chronicles-Tutorial wird ein "Regierungssitz" erwähnt, Gemeint ist da das Kapitol:
https://ibb.co/y8hnc6R

3. Ebenfalls in den Chronicles:
https://ibb.co/kB1Dzrb
Beschreibung wirr, mit englischen Namen & die Titel zu groß für die Fenster.

**Comment by Nihlo** [comment]
![h3](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/751b483a-b535-4296-8997-a80d13eb8f10)

Ein bisschen holprig liest sich das deutsche File für das SoD_SP schon noch^^ Und Keinkram, aus "week of the..." wurde "Monat der Seuche.

**Comment by Nihlo** [comment]
![h1](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/24bfc3a1-5af9-4920-9e7c-082b88dac41c)

Im letzten HD+ Update kam ein neues Checkfenster beim Scenario restart dazu.

**Comment by Nihlo** [comment]
SoD_SP bekam ein Update:
https://docs.google.com/document/d/1X2s6Nc1H4s_H_fGI85jYkoxmNKEFtq5NCs0Y8LaJvg0

**Comment by heroesiiifan** [comment]
Danke sehr. Vielleicht komme ich da mal dazu.

**Comment by Nihlo** [comment]
Noch mehr absolut unwichtiger Kleinkram:

1. 
![h3](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/9d67d35c-e5cb-4e16-9cfd-fda250a81270)
![h4](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/92296d53-df01-4bce-9025-6c30a6d8da82)

Heißt tatsächlich "Mitwirkende" statt Credits, "Übungsspiel" statt Tutorial und "Beenden" statt Ende. 

2.
Noch ein paar englische HD+ Patch Reste:
![h2](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/5ff9bcb8-25e6-4d73-ac5c-d9a2a3e0971e)

3. 
Im Custum-Kampagnen-Menü steht noch "Select a Campaign":
![h6](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/33a1b283-b57f-4fe0-9e05-e3e68a4efa79)

btw: statt alphabetische Reihenfolge der Chronicles wäre eine chronologische Reihefolge sinnvoller. Vllt mit schlichtem 1-8 davor ? Etwa:

1. Tutorial Wasteland
2. Warlord of the Wasteland
3. Tutorial Underworld
4. Conquest of the Underworld
5. Tutorial Beastmasters
6. Revolt of the Beastmasters
7. Tutorial Elements
8. Master of the Elements
9. Tutorial World Tree
10. The World Tree
11. Tutorial Moon
12. The Fiery Moon
13. Tutorial Dragons
14. Clash of the Dragons
15. Tutorial Sword
16. The Sword of Frost 

4.
Die Kampagnen-Bonus/Difficulty Auswahl ist etwas häßlich:
![H1](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/0168a944-5b9e-4b3b-a5a5-69f5ff544282)

Im Original steht zB einfach "Bonus":
![h5](https://github.com/heroesiiifan/HoMM3-German/assets/26931653/13bab7ca-651d-4573-b90f-a6835e9720ca)
wär das zumindest mal kürzer/hübscher.

5. Gab es nicht auch schon eine deutsche HD+ Launcher Datei von jemand anderem ? Finde sie nicht mehr.
