### ISSUE TITLE
Darstellungsfehler bei Sonderzeichen in VCMI (iOS version)

### ISSUE THREAD

**Issue by theoccurrence** [heroesiiifan/HoMM3-German#5]
Hi, ich bin mir nicht sicher, ob das ein allgemeines Problem ist, ob das nur ein Problem bei der iOS Version von VCMI ist, oder ob sich das überhaupt fixen lässt, aber Umlaute werden überall außer auf Buttons inkorrekt dargestellt.

Hier zwei Screenshots als Beispiel:

![image](https://user-images.githubusercontent.com/16444679/221860086-3177635a-bc15-45bb-b38a-ea1dba6bf316.png)

![image](https://user-images.githubusercontent.com/16444679/221860110-3230ccf7-a8cd-43c7-b393-c4e1f02ee1e5.jpeg)

EDIT: Andere deutsche Sonderzeichen, wie zum Beispiel das ß, sind ebenfalls betroffen.

**Comment by heroesiiifan** [comment]
Hi @theoccurrence 

sorry für die späte Antwort.

Das hat irgendwie etwas mit der Kodierung zu tun. Ich habe leider kein iOS um das zu testen. Deutsch wäre CP1252, falls man das irgendwo umstellen kann.

Du verwendest die aktuelle nightly? Hast du bei iOS die Möglichkeit die Mod-Dateien händisch auszutauschen?
Habe hier eine neuere Version, die auf den neuen Möglichkeiten der Nightlys basiert (und somit UTF-8 nutzt): [Mod für 1.2 Nightly](https://github.com/vcmi-mods/german-translation/archive/refs/heads/vcmi-1.2.zip)

**Comment by theoccurrence** [comment]
Hi @heroesiiifan vielen Dank für die Hilfe!

Ja, ich kann Mod-Dateien händisch austauschen. Ich habe das update ausprobiert, aber leider ist besagter Darstellungsfehler unverändert...
Allerdings sind nun deutlich mehr Menü-Elemente unübersetzt.

![image](https://user-images.githubusercontent.com/16444679/225625159-d64d8335-a507-4cc5-a7f3-bca2cddff84d.jpeg)

Falls ich beim Testen irgendetwas helfen kann, biete ich mich gerne an :)

EDIT: Ich habe gerade gesehen dass es seit 5 tagen eine 1.9.3 version gibt, die aktuellste Version in https://github.com/vcmi-mods/german-translation ist 1.9.2.

**Comment by heroesiiifan** [comment]
Habe nun doch ein  iOS-Gerät da zum ausprobieren. Nach dem etwas umständlichen Sideload hab ich es am laufen.

Bei mir ging es einwandfrei. Habe die aktuellste nightly von Github geladen. Der Launcher ist leider noch etwas buggy. Am besten bei englisch bleiben. Bei jeder anderen sprache hatte ich einen (nur durch neuinstallation behebaren) Freeze.

Habe VCMI installiert, die H3 Orginal-Dateien reinkopiert. Händisch ein die oben verlinkte German-Version in den Mods Ordner gebracht und anschließend VCMI gestartet, den Launcher durchgeklickt (englisch) und dann auf Deutsch gestellt. Dann hat es anstandslos funktioniert...

Habe sogar ein paar Städte nachinstalliert (Achtung: Nicht alle funktionieren).

![1](https://user-images.githubusercontent.com/77574150/225765435-ca24e3d8-ec32-471d-afe3-b97f751f0675.png)
![2](https://user-images.githubusercontent.com/77574150/225765412-4c2b671b-5765-4db9-b50b-952578b989fe.png)
![3](https://user-images.githubusercontent.com/77574150/225765361-265ed7c5-3654-4fa1-83b0-4f5a102b34ce.png)

**Comment by theoccurrence** [comment]
Hi @heroesiiifan 

Ohje, kann sein dass ich vielleicht etwas blöd bin, aber was genau meinst du mit
> den Launcher durchgeklickt (englisch) und dann auf Deutsch gestellt. Dann hat es anstandslos funktioniert...

Ich erzähl mal genau, was ich probiert habe, vielleicht kommen wir dann darauf, was genau ich falsch mache.

- Die 1.9.2 Version im Launcher installieren, und danach entweder den contents ordner oder den kompletten Inhalt mit der entpackten Nightly zu ersetzen, übersetzt bei mir nahezu gar nichts. Einzig den Zurück Button und die "Szenario-Name!" Überschrift.

![image](https://user-images.githubusercontent.com/16444679/226178100-84400a66-b466-4289-9e7c-6c653775376f.png)

- Wenn ich den Inhalt einfach in den Mod Ordner kopiere, dann bekomme ich in VCMI einen neuen Eintrag für die deutsche Übersetzung mit der Version 1.9.3, allerdings wird sie als deaktiviert (mit dem durchgestrichenen roten Kreis) angezeigt. Offensichtlich ist sie aber trotzdem aktiviert, denn es hat einen Einfluss auf das Spiel und wenn ich auf "enable" klicke, dann friert VCMI komplett ein.

![image](https://user-images.githubusercontent.com/16444679/226178409-a06bee1d-61e1-461f-bf93-62b372be12cb.png)

- Ich habe auch geschaut ob man im Spiel irgendwo die Sprache ändern kann, aber das scheint auch nicht zu gehen.

Warum wird mir in VCMI 1.9.2 als neueste Version angezeigt, obwohl es auf deinem GitHub eine 1.9.3 version gibt? Ich hab die mir mal runtergeladen, aber das ist eine komplett andere Ordnerstruktur als der Mod, den du mir verlinkt hast, darum keine Ahnung was ich damit machen soll.

Es ist auch nicht der Weltuntergang wenn es nicht funktioniert, aber ein Bisschen schade ist es schon.

Falls es dir weiterhilft: ich benutze ein iPhone 12 pro max mit iOS 16.2.
Ich denke aber nicht dass es damit zusammenhängt, denn wie gesagt funktioniert die 1.9.2 version bis auf falsche Codierung ja fast.

Vielen Dank für die Hilfe

EDIT:

Okay, ich habe jetzt alle Mods nach und nach eingeschaltet, und jetzt bin ich wieder auf dem stand vom Anfang, nämlich falsch angezeigte Sonderzeichen. Ich habe aber herausgefunden an welchem Mod es liegt. Es scheint leider eine Inkompatibilität mit Horn of the Abyss vorzuliegen, was mit gewaltigem Abstand mein Lieblingsmod ist, und ich eigentlich als nativen Teil des Spiels betrachte.

Screenshot mit HotA deaktiviert:

![image](https://user-images.githubusercontent.com/16444679/226179274-8c804985-accd-487a-bd63-0ace6a6ab4fc.png)

Screenshot mit HotA aktiviert:

![image](https://user-images.githubusercontent.com/16444679/226179284-7074d310-da49-4684-a298-71fc9709d9ea.png)

Die unübersetzten Elemente auf den Screenshots habe ich mittlerweile wieder auf Deutsch gekriegt. Man musste nur den Deutsch-Mod als aller erstes aktivieren, und dann nach und nach alle anderen Mods außer HotA, und jetzt ist alles korrekt übersetzt und formatiert, nur HotA fehlt eben ...

**Comment by heroesiiifan** [comment]
Hi @theoccurrence 

ah. Ich denke, du hast nicht die aktuelle Nightly. Da gehen aber dafür andere Dinge nicht. VCMI ist gerade stark in Überarbeitung.

Ich denke zu deinem konkreten Problem könnte es helfen, wenn du bei HotA auf den kleinen Pfeil klickst und da die Submod "HotA fonts" deaktivierst.

Die 1.9.3 ist nur für die aktuellsten Nightlies. Wenn du eine ältere Version hast (z.B. offizielles Release) dann hast du unübersetzte Texte, weil die Technik, wie Übersetzungen funktionieren geändert wurde.

**Comment by theoccurrence** [comment]
@heroesiiifan 

Tatsächlich... Die HotA fonts waren's.
Ich wusste nicht dass man das noch aufklappen kann, dieser kleine Pfeil ist mir nie aufgefallen.

Vielen Dank für alles :)

**Comment by heroesiiifan** [comment]
@theoccurrence Super und kein Problem :)
