### ISSUE TITLE
Alternative Übersetzungen für HotA

### ISSUE THREAD

**Issue by Libavi** [heroesiiifan/HoMM3-German#7]
Erst einmal vielen Dank für das tolle Repo und die Möglichkeit HoMM3 Complete und HotA endlich auf deutsch spielen zu können.

Ich hätte die neuen Kreaturen bei HotA z.T. anders übersetzt und wollte hier nur einmal eine offene Diskussion anregen. Das heißt nicht, dass ich meine, dass meine Vorschläge alle übernommen werden sollen.

LG
Libavi

| **<br>**          | **<br>**             | **heroesiiifan**    | **<br>**            | **Libavi**         | **<br>**          |                                                                                                                                        |
| ----------------- | -------------------- | ------------------- | ------------------- | ------------------ | ----------------- | -------------------------------------------------------------------------------------------------------------------------------------- |
| **Russisch**      | **Englisch**         | **Singular**        | **Plural**          | **Singular**       | **Plural**        | **Begründung**                                                                                                                         |
| Океанида      | Oceanid              | Okeanide            | Okeaniden           | Ozeanide           | Ozeaniden         | Analog zu Zentaur und Zyklop statt Kentaur und Kyklop. Vgl. Ozean statt Okean.                                                         |
| Матрос            | Crew Mate            | Crewmitglied        | Crewmitglieder      | Matrose            | Matrosen          | Direkt aus dem Russischen (Матрос)                                                                                                     |
| Ассида            | Ayssid               | Ayssid              | Ayssiden            | Assida             | Assiden           | Näher am russischen Original                                                                                                           |
| Никс              | Nix                  | Nixe                | Nixen               | Nix                | Nixe              | Nixe ist das weibliche Wesen, Nix das männliche ([https://www.duden.de/rechtschreibung/Nix](https://www.duden.de/rechtschreibung/Nix)) |
| Аспид             | Haspid               | Haspid              | Haspids             | Aspid              | Aspide            | Näher am russichen Original                                                                                                            |
| Броненосец        | Armadillo            | Armadillo           | Armadillos          | Gürteltier         | Gürteltiere       | Armadillo sollte übersetzt werden                                                                                                      |
| Броненосец-Вожак  | Bellwether Armadillo | Armadillo Vorreiter | Armadillo Vorreiter | Gürteltierführer    | Gürteltierführer  |                                                                                                                                        |
| Автоматон         | Automaton            | Automaten           | Automaten           | Automaton          | Automata          | Von u.a. Frostpunkt übernommen. Automat ist im deutschen zu generisch.                                                                 |
| Автоматон-Часовой | Automaton Sentinel   | Wächterautomat      | Wächterautomaten    | Wächter-Automaton  | Wächter-Automata  |                                                                                                                                        |
| Коатль            | Couatl               | Couatl              | Couatls             | Couatl             | Couatl            | Plural einfach gleich dem Singular(vgl. [https://drachen.fandom.com/de/wiki/Couatl](https://drachen.fandom.com/de/wiki/Couatl))        |
| Багровый Коатль   | Crimson Couatl       | Karminroter Couatl  | Karminrote Couatls  | Karminroter Couatl | Karminrote Couatl |                                                                                                                                        |
| Лепрекон          | Leprechaun           | Kobold              | Kobolde             | Leprechaun         | Leprechauns       | Kobold ist zu generisch, ggf wird er noch woanders benötigt.                                                                           |
| Сатир             | Satyr                | Satyr               | Satyren             | Satyr              | Satyrn            | Der korrekte Plural laut Duden ist Satyrn ([https://www.duden.de/rechtschreibung/Satyr](https://www.duden.de/rechtschreibung/Satyr))   |

**Comment by Libavi** [comment]
Bei Gürteltierführer (analog zu Zentaurenführer) bin ich noch unzufrieden. Die präziseste Übersetzung wäre Leit-Gürteltier, analog zu Leittier, Leithengst, Leitwolf. Das klingt aber albern.
Vielleicht auch einfach noch freier übersetzen. (So wie zum Biespiel Powerlich -> Todeslich, Mighty Gorgon -> Riesengorgone im Original)

**Comment by heroesiiifan** [comment]
done
